services:
  db:
    image: mongo:3
    container_name: db

  web:
    depends_on:
      - db
    container_name: web

    image: node:6.9.1
    command: node /work/server.js
    ports:
      - 127.0.0.1:3000:3000

    working_dir: /work
    volumes:
      - .:/work
    
    environment:
      - MONGO_IP=db

  test:
    depends_on:
      - db
      - web
    container_name: test

    image: node:6.9.1
    command: curl -s http://web:3000

    working_dir: /work
    volumes:
      - .:/work

      